### ISSUE TITLE
[Question] SabinaTable dictionary

### ISSUE THREAD

**Issue by Wiratama23** [UcanPatatess/SND-FullAuto#2]
{0, GordianBoltID, BoltBuyAmount, 11506, 22,0}

can i have an explanation on what these things mean to?

i only know index 1,2,3,4 but not 0 and 5

filename GlobalTurnIn.lua

**Comment by UcanPatatess** [comment]
yes of course the index 0 is for the shops in the same NPC so should be used as SelectString 0 or SelectString 1 ex.
there is 3 shops in Sabina npc so in sabina table it is used as 0,1,2

index 5 is the location of the item in the shop menu starts from 0 and should end with 22 because there is only 23 items in turn in shop some shops has less than 23 like shop 2/dow2 for Sabina has 14items to exchange

**Comment by Wiratama23** [comment]
ok thanks!
